In [90]:
with open('input.txt', 'r') as f:
    lines = f.read().splitlines()
folds = lines[-12:]
dots = lines[:-13]

In [76]:
with open('easy.txt', 'r') as f:
    lines = f.read().splitlines()
folds = lines[-2:]
dots = lines[:-3]

In [105]:
import numpy as np
max_x, max_y = 0, 0
for fold in folds:
    axis, size = fold.split(' ')[-1].split('=')
    if axis == 'x' and int(size) > max_x:
        max_x = int(size)
    if axis == 'y' and int(size) > max_y:
        max_y = int(size)
    
paper = np.full((max_y * 2 + 1, max_x * 2 + 1), 0)

for dot in dots:
    x, y = map(lambda x: int(x), dot.split(','))
    paper[y][x] = 1
    
def fold_paper(paper, axis, line):
    if axis == 'x':
        left = paper[:, :line]
        right = paper[:, line+1:]
        mirror_right = np.flip(right, 1)
        left[:, -right.shape[1]:] += mirror_right
        return left
    else:
        up = paper[:line, :]
        down = paper[line+1:, :]
        mirror_down = np.flip(down, 0)
        up[-down.shape[0]:, :] += mirror_down
        return up
        
print(paper)
for fold in folds:
    axis, line = fold.split(' ')[-1].split('=')
    paper = fold_paper(paper, axis, int(line))
    print(len(paper[np.where(paper > 0)]))
    print(paper)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
755
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
622
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
517
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
427
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
351
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
295
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
241
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
197
[[0 0 0 

In [101]:
print('ol')
for i, row in enumerate(paper):
    row = ''
    for j, value in enumerate(paper[i]):
        if paper[i][j] > 0:
            row += '#'
        else:
            row += '.'
    print(row)
print('ll')

ol
###..#....#..#...##.###..###...##...##..
#..#.#....#.#.....#.#..#.#..#.#..#.#..#.
###..#....##......#.#..#.###..#..#.#....
#..#.#....#.#.....#.###..#..#.####.#.##.
#..#.#....#.#..#..#.#.#..#..#.#..#.#..#.
###..####.#..#..##..#..#.###..#..#..###.
ll


In [93]:
paper

array([[ 8, 21,  2,  0,  0, 10,  0,  0,  0,  0,  1,  0,  0,  3,  0,  0,
         0,  7, 13,  0,  2,  2,  5,  0,  0,  2, 17,  4,  0,  0,  0, 20,
        25,  0,  0,  0,  5,  7,  0,  0],
       [30,  0,  0,  8,  0, 19,  0,  0,  0,  0,  6,  0, 13,  0,  0,  0,
         0,  0, 11,  0, 10,  0,  0, 21,  0, 11,  0,  0, 24,  0,  9,  0,
         0,  7,  0,  1,  0,  0,  7,  0],
       [25, 10,  1,  0,  0, 11,  0,  0,  0,  0, 10,  1,  0,  0,  0,  0,
         0,  0,  4,  0,  2,  0,  0,  4,  0,  5,  2,  4,  0,  0,  2,  0,
         0,  4,  0,  2,  0,  0,  0,  0],
       [10,  0,  0,  2,  0,  8,  0,  0,  0,  0, 14,  0, 20,  0,  0,  0,
         0,  0,  5,  0, 12,  5,  5,  0,  0, 13,  0,  0,  6,  0,  2,  1,
         9,  7,  0,  8,  0,  3, 12,  0],
       [11,  0,  0,  3,  0, 13,  0,  0,  0,  0,  5,  0,  6,  0,  0,  6,
         0,  0, 11,  0, 29,  0,  9,  0,  0, 18,  0,  0,  2,  0,  7,  0,
         0,  1,  0,  6,  0,  0,  6,  0],
       [ 3,  7, 13,  0,  0,  8, 21,  7, 13,  0,  3,  0,  0, 12,  0,  0,
   